# Generated by Django 5.0.4 on 2024-04-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
