# Generated by Django 5.0.4 on 2024-04-28 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_menuitem_description_menuitem_nutritional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='nutritional_info',
        ),
    ]
