# Generated by Django 5.0.4 on 2024-05-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_menuitem_nutritional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Breads', 'Breads'), ('Deserts', 'Deserts')], max_length=50),
        ),
    ]
